version: "3"

services:
  ark-ded:
    container_name: ark-ded
    image: lyuhau/ark-ast:${BRANCH:-mods}
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    network_mode: host
#    ports:
#      - 27015:27015/udp
#      - 7777:7777/udp
#      - 7778:7778/udp
#      - 27020:27020/tcp
    privileged: true
    volumes:
      - ./arkmanager.cfg:/etc/arkmanager/arkmanager.cfg
      - ./instances/main.cfg:/etc/arkmanager/instances/main.cfg
      - ./ARK-Backups:/home/steam/ARK-Backups
    command: ["sh", "-c", "arkmanager update --update-mods && arkmanager restore && arkmanager run"]
